name: dragonfly_browservault
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.6.0-149.3.beta

# Add regular dependencies here.
dependencies:
  sqlite3: ^2.4.6


dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
