name: dragonfly_css_parser
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: ^3.6.0-149.3.beta

dependencies:
  petitparser: ^6.0.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
